# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('context', models.CharField(max_length=250)),
                ('desired_result', models.CharField(max_length=250)),
                ('netlist', models.CharField(max_length=250)),
                ('datatime_order', models.DateTimeField()),
                ('datatime_accom', models.DateTimeField()),
                ('datatime_approv', models.DateTimeField()),
                ('datatime_deadline', models.DateTimeField()),
                ('datatime_finished', models.DateTimeField()),
                ('list_number', models.CharField(max_length=250)),
                ('list_code', models.CharField(max_length=250)),
                ('href_blank', models.CharField(max_length=250)),
                ('href_finished', models.CharField(max_length=250)),
                ('href_results', models.TextField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Themes')),
            ],
        ),
    ]
