# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='needed_otk',
            field=models.BooleanField(default='TRUE'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='needed_vp',
            field=models.BooleanField(default='TRUE'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='worker',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
