# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160415_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
