# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160415_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='worker',
        ),
    ]
