# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_tasks_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='needed_otk',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='needed_vp',
        ),
    ]
