# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_auto_20160415_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='needed_otk',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tasks',
            name='needed_vp',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tasks',
            name='worker',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
