# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160415_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='needed_otk',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='needed_vp',
            field=models.BooleanField(),
        ),
    ]
